### PR TITLE
SBP M1 review

### PR DESCRIPTION
**Pull request by stiiifff**

### CODE REVIEW

**Comment by RoyTimes** [comment]
Hi @stiiifff , sorry for the delay. We will get to this once we merge the other PR soon. Expect one more week or so.

**Comment by stiiifff** [comment]
Sure, no worries

**Comment by RoyTimes** [comment]
@stiiifff All issues that you pointed out are fixed in https://github.com/skyekiwi/skyekiwi-network/pull/20. There are changes in the blockchain runtime that makes it infeasible to merge this PR without going through tons of changes. 

Please take a look and feel free to propose more changes. Sorry again for the delay.

**Comment by stiiifff** [comment]
No prob, thanks for pinging me. Btw, what do you mean by "_maybe update weight on a low end machine instead_" ?

**Comment by RoyTimes** [comment]
The weight was initially generated on my M1 Pro MacBook. I realized that my machine takes 4mins to compile the whole codebase and might be really off on the benchmarking. So we put the benchmarking on a old 6th gen Intel machine and regenerated the benchmark at https://github.com/skyekiwi/skyekiwi-network/pull/20/commits/b2f6f96c437d79a3a506b4a17ea70584eb0046de

**Comment by stiiifff** [comment]
The benchmarks should be ran on hardware specs that you deem to be the reference hardware platform for validator nodes in your network, so that the generated weights will represent real-word measurement of computational effort (to produce blocks).
More info here: https://docs.substrate.io/v3/runtime/benchmarking/

**Comment by RoyTimes** [comment]
@stiiifff Yup. That's exactly what we done. We generated the weights on an old metal machine with `Intel(R) Xeon(R) CPU E3-1225 v5` with 8GB of memory with Intel SGX support. It's a 7 year old low-end CPU. It should correctly assume the worst case scenario for node operators.

**Pull request closed without merging**
